[build-system]
requires = ["setuptools>=64", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "trompy"
dynamic = ["version"]
description = "A collection of tools for data analysis and plotting that originated in the McCutcheon Lab (UiT, Tromso)"
readme = "README.md"
license = {text = "MIT"}
authors = [
    {name = "James E McCutcheon", email = "j.mccutcheon@uit.no"}
]
keywords = ["neuroscience", "behavior"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Topic :: Software Development :: Build Tools",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
]
requires-python = ">=3.8"
dependencies = [
    "numpy",
    "matplotlib",
    "xlrd",
    "scipy",
    "pandas",
    "xlsxwriter",
    "tdt",
    "openpyxl",
]

[project.urls]
Homepage = "https://github.com/mccutcheonlab"
Repository = "https://github.com/mccutcheonlab/trompy"
# Download URL auto-generated by setup.py from version

[tool.setuptools]
packages = ["trompy"]

[tool.setuptools.dynamic]
version = {attr = "trompy._version.__version__"}
